// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byilgvjorlntlldvjexq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5aWxndmpvcmxudGxsZHZqZXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNzQ5MTksImV4cCI6MjA4NjY1MDkxOX0.C_NVXPpKc-9rEquqF86ph7vi4GcDw2oc3MtJn8JcfQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});